name: Test and Push To Registry

on:
  pull_request:
  push:
    tags: ["v*"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy: &db-matrix
      fail-fast: false
      matrix:
        include:
          - db: postgres
            variant: base

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3

      - name: Test
        run: just test ${{ matrix.db }} ${{ matrix.variant }}

      - name: Cleanup
        if: always()
        run: just down-all ${{ matrix.db }} ${{ matrix.variant }}

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    strategy: *db-matrix

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3

      - name: Push
        run: just push ${{ matrix.db }} ${{ matrix.variant }}

      - name: Cleanup
        if: always()
        run: just down-all ${{ matrix.db }} ${{ matrix.variant }}
